### PR TITLE
Block libre.tube

### PR DESCRIPTION
**Pull request by KellerFuchs**
See https://im-in.space/@kdy/102264474927313787 for further context.
This also needs to be acted on with the actual block.

### CODE REVIEW

**Comment by KellerFuchs** [comment]
I wasn't sure what was the right channel to suggest a block (and I'd rather not subject admins to that kind of crud over IM).  Apologies if I was wrong to send a PR here.

**Comment by rtucker** [comment]
DMing tastymochafox and/or mxsparks, or e-mailing admins@vulpine.club, is the usual way to go.  I'll assign this to them tho :)

**Comment by KellerFuchs** [comment]
Oooh, thanks, I didn't realise there was an email alias.

**Comment by mxsparks** [comment]
Sometimes people also just report the toot and put something like “instance block recommendation for [site]” in the comments section, which also sends us an email alert. I’ve just suspended libre.tube, working on the announcement now.

**Pull request merged**
